// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krxnvjbdivryeafnqker.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyeG52amJkaXZyeWVhZm5xa2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjU3MTUsImV4cCI6MjA2OTM0MTcxNX0.umLe8o8ZHxS9-rZYlYL9RZD5yA2xUgxV6tURtkMGZys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});